# for model 1-3

In [1]:
from keras.models import load_model
import pandas as pd # 引用套件並縮寫為 pd  

Using TensorFlow backend.


In [2]:
model = load_model('model/model_V3.h5') 

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [3]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_7 (Embedding)      (None, None, 32)          32000     
_________________________________________________________________
lstm_12 (LSTM)               (None, None, 32)          8320      
_________________________________________________________________
lstm_13 (LSTM)               (None, None, 32)          8320      
_________________________________________________________________
lstm_14 (LSTM)               (None, 32)                8320      
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 33        
Total params: 56,993
Trainable params: 56,993
Non-trainable params: 0
_________________________________________________________________


In [4]:
data_test = pd.read_csv('data/test.csv')  
print(data_test) 

         id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather 

In [5]:
data_test=data_test[['id','text']]
data_test

id                                               text
0         0                 Just happened a terrible car crash
1         2  Heard about #earthquake is different cities, s...
2         3  there is a forest fire at spot pond, geese are...
3         9           Apocalypse lighting. #Spokane #wildfires
4        11      Typhoon Soudelor kills 28 in China and Taiwan
...     ...                                                ...
3258  10861  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...
3259  10865  Storm in RI worse than last hurricane. My city...
3260  10868  Green Line derailment in Chicago http://t.co/U...
3261  10874  MEG issues Hazardous Weather Outlook (HWO) htt...
3262  10875  #CityofCalgary has activated its Municipal Eme...

[3263 rows x 2 columns]

In [6]:
import pickle
# loading
with open('tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

In [7]:
data_test_=data_test['text']

In [8]:
'''tokenizer.fit_on_texts(data_test_)
seq=tokenizer.texts_to_sequences(data_test_)
seq'''

'tokenizer.fit_on_texts(data_test_)\nseq=tokenizer.texts_to_sequences(data_test_)\nseq'

In [9]:
one_hot_seq=tokenizer.texts_to_matrix(data_test_,mode='binary')
one_hot_seq

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
one_hot_seq.shape

(3263, 1000)

In [11]:
res=model.predict(one_hot_seq)
res

array([[0.24513537],
       [0.24513751],
       [0.24513751],
       ...,
       [0.24347274],
       [0.2451375 ],
       [0.2451375 ]], dtype=float32)

In [12]:
res[res>0.5]=1
res[res<=0.5]=0
res

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [13]:
data_test['target']=res

In [14]:
res=data_test[['id','target']]
res

id  target
0         0     0.0
1         2     0.0
2         3     0.0
3         9     0.0
4        11     0.0
...     ...     ...
3258  10861     0.0
3259  10865     0.0
3260  10868     0.0
3261  10874     0.0
3262  10875     0.0

[3263 rows x 2 columns]

In [15]:
res['target']=pd.to_numeric(res['target'], downcast='integer')

C:\Users\highs\anaconda3\envs\tensorflow-gpu\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [16]:
res.to_csv('Kaggle-3.csv',index=False)